# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:16.20.0

pipelines:
  branches:
   
   staging:
     - step:
          name: Deploy to develop
          caches:
              - node
          script:
              - apt-get update 
              - apt-get install -y rsync # install rsync
              - apt-cache search rsync # check if apt can find rsync
              - ssh-keyscan -H $SSH_SERVER_IP >> ~/.ssh/known_hosts
              - ssh ubuntu@$SSH_SERVER_IP 'sudo rm -rf /var/www/XSApiSTG/*'
              - rsync -r -v -e ssh . ubuntu@$SSH_SERVER_IP:/var/www/XSApiSTG --delete-before --exclude '.git'
              - ssh ubuntu@$SSH_SERVER_IP 'cd /var/www/XSApiSTG && npm i &&npm run build && pm2 stop XSApiSTG && pm2 delete XSApiSTG && pm2 start npm --name "XSApiSTG" -- run start:prod'
              - echo 'Develop deployment XSApiSTG DONE!'
