export enum ID_C_PAYMENT_STATUS {
  PENDING = 1,
  UNPAID = 2,
  PAID = 3,
  PARTIALLY = 4,
  EXTRA = 5,
}

export enum ID_C_TYPE_OF_PAYMENT {
  SETTLED = 1,
  PARTIAL_PAYMENT = 2,
  REMAINING_DEBT = 3,
}
